# BlockRegen
#
# Generated on version: ${project.version}
# Wiki: https://github.com/Wertik/BlockRegen/wiki

# Enable for players with `blockregen.admin` permission to get notified of a plugin update when they join.
Update-Checker: true

# Enable debug logging in the console.
#
# If you cannot figure out why something doesn't work,
# this might give you a better insight into what the plugin is doing.
Debug-Enabled: false

# Enable regions.
#
# Set to true if you wish to use regeneration regions (areas) instead of worlds.
# Set to false for the plugin to regenerate blocks in whole worlds as per Worlds-Enabled.
Use-Regions: true

# Don't allow players to break blocks outside those configured for regeneration.
#
# Setting this to true protects all other blocks from being broken. No other protection is provided.
# Setting this to false allows the players to break any other block freely.
Disable-Other-Break: true

# Worlds in which the plugin regenerates blocks.
#
# Only used when Use-Regions is set to false.
Worlds-Enabled:
  - world

# When set to true, players in creative game-mode will bypass regeneration and protection.
# When a regenerating block is broken (aka the replace-block), the process is cancelled, and it doesn't regenerate.
Bypass-In-Creative: true

# Enable to manually give out Jobs rewards.
# Sometimes this causes duplicated rewards. If that happens, disable them here.
Jobs-Rewards: true

# Setting this to true makes the plugin respect Towny protection.
# If a block inside a town is broken and is protected against the player breaking it. Nothing will happen.
Towny-Support: true

# Setting this to true makes the plugin respect GriefPrevention protection.
# If a block inside a protective region is broken and is protected against the player breaking it. Nothing will happen.
GriefPrevention-Support: true

# Setting this to true makes the plugin respect WorldGuard protection.
# If a block inside a WorldGuard region is broken and is protected against the player breaking it. Nothing will happen.
WorldGuard-Support: true

# Setting this to true makes the plugin respect Residence protection.
# If a block inside a residence is broken and is protected against the player breaking it. Nothing will happen.
Residence-Support: true

# Periodically save running regeneration processes and regions.
Auto-Save:
  Enabled: true
  # Interval in seconds
  Interval: 600
